Repository yiisoft/view, pull requests merged in 2021-05, with the labels that each got.

#139 Fixed error on WebView::renderAjax with path relative to basePath
  src/Event/ViewEvent.php
  src/View.php
  tests/WebViewTest.php
  tests/public/view/only-content.php
Labels: status:code review, type:bug

#138 Add WebView::registerScriptTag
  composer.json
  src/WebView.php
  tests/WebViewTest.php
Labels: status:code review

#145 Rename WebView::setJsVar() to WebView::setJsVars() and change syntax for set JS vars and strings
  src/WebView.php
  tests/WebViewTest.php
Labels: status:code review

#144 Disallow definition objects in configs, except ReferenceInterface
  config/common.php
  config/web.php
Labels: status:ready for merge

#148 Adopt to new yiisoft/assets
  src/WebView.php
  tests/WebViewTest.php
  tests/public/view/positions.php
Labels: status:code review

#143 Finalize View and WebView + remove yiisoft/i18n
  composer.json
  src/BaseView.php
  src/PhpTemplateRenderer.php
  src/TemplateRendererInterface.php
  src/View.php
  src/WebView.php
  tests/Mocks/WebViewPlaceholderMock.php
  tests/TestCase.php
  tests/WebViewTest.php
  tests/public/view/layout.php
Labels: status:code review

#141 Add WebView::renderString()
  src/WebView.php
  tests/WebViewTest.php
Labels: status:code review

#149 Tests refactoring
  composer.json
  tests/TestCase.php
  tests/TestSupport/TestHelper.php
  tests/TestSupport/TestTrait.php
  tests/ThemeTest.php
  tests/ViewTest.php
  tests/WebViewTest.php
  tests/public/tmp/.gitignore
Labels: status:code review, type:test

#150 Remake events
  src/BaseView.php
  src/Event/AfterRender.php
  src/Event/AfterRenderEventInterface.php
  src/Event/BeforeRender.php
  src/Event/BodyBegin.php
  src/Event/BodyEnd.php
  src/Event/PageBegin.php
  src/Event/PageEnd.php
  src/Event/View/AfterRender.php
  src/Event/View/BeforeRender.php
  src/Event/View/PageBegin.php
  src/Event/View/PageEnd.php
  src/Event/View/ViewEvent.php
  src/Event/ViewEvent.php
  src/Event/WebView/AfterRender.php
  src/Event/WebView/BeforeRender.php
  src/Event/WebView/BodyBegin.php
  src/Event/WebView/BodyEnd.php
  src/Event/WebView/Head.php
  src/Event/WebView/PageBegin.php
  src/Event/WebView/PageEnd.php
  src/Event/WebView/WebViewEvent.php
  src/View.php
  src/WebView.php
  tests/Event/View/AfterRenderTest.php
  tests/Event/View/BeforeRenderTest.php
  tests/Event/View/PageBeginTest.php
  tests/Event/View/PageEndTest.php
  tests/Event/View/ViewEventTest.php
  tests/Event/WebView/AfterRenderTest.php
  tests/Event/WebView/BeforeRenderTest.php
  tests/Event/WebView/BodyBeginTest.php
  tests/Event/WebView/BodyEndTest.php
  tests/Event/WebView/HeadTest.php
  tests/Event/WebView/PageBeginTest.php
  tests/Event/WebView/PageEndTest.php
  tests/Event/WebView/WebViewEventTest.php
  tests/TestSupport/TestHelper.php
  tests/ViewTest.php
  tests/WebViewTest.php
Labels: status:code review

#152 Psalm level 2
  psalm.xml
  src/BaseView.php
  src/PhpTemplateRenderer.php
  src/View.php
  src/WebView.php
Labels: status:code review

#151 Add tests
  tests/WebViewTest.php
Labels: status:code review

#153 Rename WebView methods setJsFiles, setJsStrings, setJsVars, setCssFiles, setCssStrings to add*
  src/WebView.php
  tests/WebViewTest.php
Labels: status:code review

#155 Refactoring default parameters feature to BaseView
  src/BaseView.php
  tests/ViewTest.php
Labels: status:code review

#157 Fix configuration due to refactoring default parameters
  config/common.php
  config/params.php
  config/web.php
Labels: status:code review

#158 Add setCommonParameters() method to BaseView
  config/common.php
  config/web.php
  src/BaseView.php
Labels: status:code review

#154 Add methods WebView::registerMeta() and WebView::registerLink() + support position for link tags
  src/BaseView.php
  src/WebView.php
  tests/WebViewTest.php
Labels: status:code review
