Repository yiisoft/view, pull requests merged in 2021-06, with the labels that each got.

#160 Add reset to configurations, add BaseView::clear() method
  config/common.php
  config/web.php
  src/BaseView.php
  src/WebView.php
Labels: status:code review

#162 Remove logger usage
  composer.json
  src/BaseView.php
  tests/TestSupport/TestHelper.php
Labels: status:code review

#164 Add more tests
  src/WebView.php
  tests/CachedContentTest.php
  tests/ViewTest.php
  tests/WebViewTest.php
Labels: type:test

#166 Add more tests
  src/BaseView.php
  tests/Event/View/BeforeRenderTest.php
  tests/Event/WebView/BeforeRenderTest.php
  tests/ViewTest.php
  tests/WebViewTest.php
Labels: status:code review, type:test

#167 Cleanup, improve psalm, improve rendering views starting with slash
  .editorconfig
  .gitattributes
  .github/dependabot.yml
  .github/workflows/bc.yml_
  .github/workflows/build.yml
  .github/workflows/mutation.yml
  .github/workflows/static.yml
  .phpunit-watcher.yml
  .scrutinizer.yml
  .styleci.yml
  CHANGELOG.md
  README.md
  phpunit.xml.dist
  psalm.xml
  src/BaseView.php
  src/Cache/CachedContent.php
  src/Cache/DynamicContent.php
  src/Event/WebView/AfterRender.php
  src/PhpTemplateRenderer.php
  src/TemplateRendererInterface.php
  src/Theme.php
  src/View.php
  src/ViewContextInterface.php
  src/WebView.php
  tests/ThemeTest.php
  tests/ViewTest.php
  tests/WebViewTest.php
Labels: status:code review

#168 Fix bug, minor improvements, more tests, test coverage 100%, MSI 99%
  src/PhpTemplateRenderer.php
  src/Theme.php
  tests/CachedContentTest.php
  tests/PhpTemplateRendererTest.php
  tests/ThemeTest.php
  tests/WebViewTest.php
  tests/public/view/error.php
  tests/public/view/rawlayout.php
Labels: status:code review
